# Generated by Django 3.0.3 on 2020-08-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('res_id', models.CharField(max_length=10)),
                ('dises_name', models.CharField(max_length=20)),
                ('dises_price', models.FloatField()),
            ],
        ),
    ]
