# Generated by Django 3.0.3 on 2020-08-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200826_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='Dises',
            new_name='dises',
        ),
    ]
